config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords     => "users/passwords"
  }
  # resources :users, only: [:index]
  devise_scope :user do
    get 'users/signuplist' => 'users/registrations#signuplist'
    post 'users/signuplist' => 'users/registrations#signuplist'
    post 'users/create' => 'users/registrations#create'
    get 'users/complete' => 'users/registrations#complete'
    # post 'users/complete_submit' => 'users/registrations#complete_submit'
    get 'users/index' => 'users/registrations#index'
    get 'users/:id' => 'users/registrations#show'
    # ↓な気もしますのでrails routesコマンドなどで確認してください
    # get 'signuplist' => 'users/registrations#signuplist'
  end

  resources :credit_cards, only: [:new, :show] do
    collection do
      post 'show',   to: 'credit_cards#show'
      post 'pay',    to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end

  resources :products, only: [:new,:create,:show,:edit,:update,:destroy] do
    collection do
      get 'category/get_category_children', to: 'products#get_category_children', defaults: { format: 'json' }
      get 'category/get_category_grandchildren', to: 'products#get_category_grandchildren', defaults: { format: 'json' }
      get 'update_done'
    end
    member do
      post 'purchase'
      get  'buy'
    end
  end
  
  resources :mypage, only: [:index] do
    collection do
      get :logout
      get :credit
    end
  end
  
  resources :users, only: [:new] 
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController

  require "payjp"
  before_action :move_to_index
  before_action :set_card, only: [:new, :delete, :show]

  def new
    redirect_to action: "show" if @card.present?
  end

  def pay
    Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_SECRET_KEY]

    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
        description: 'test',
        email: current_user.email,
        card: params['payjp-token'],
        metadata: {user_id: current_user.id}
      )

      @card = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to credit_card_path(@card.id)
      else
        redirect_to action: "show"
      end
    end
  end

  def delete
    if @card.present?
      Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_SECRET_KEY]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
    end
      redirect_to credit_mypage_index_path(@card_id)
  end

  def show
    if @card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_SECRET_KEY]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
      @card_brand = @default_card_information.brand
      case @card_brand
      when "Visa"
        @card_src = "visa.png"
      when "JCB"
        @card_src = "jcb.png"
      when "MasterCard"
        @card_src = "master.png"
      when "American Express"
        @card_src = "americanexpress.png"
      when "Diners Club"
        @card_src = "dinersclub.png"
      when "Discover"
        @card_src = "discover.gif"
      end
    end
  end

  private
  def set_card
    @card = CreditCard.find_by(user_id: current_user.id) if CreditCard.find_by(user_id: current_user.id).present?
  end

  def move_to_index
    redirect_to root_path unless user_signed_in?
  end
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/new.html.haml
= render 'shared/header'

.credit_cards-new
  .credit_cards-new__wrapper
    .credit_cards-new__wrapper__title
      クレジットカード情報入力
    .credit_cards-new__wrapper__form
      = form_tag(pay_credit_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
        .credit_cards-new__wrapper__form__cardnumber
          %label カード番号
          %span 必須
          = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
          %br
        .credit_cards-new__wrapper__form__logos
          = image_tag "visa.png", height: '33', width: '46'
          = image_tag "master.png", height: '33', width: '46'
          = image_tag "jcb.png", height: '33', width: '46'
        .credit_cards-new__wrapper__form__expiration-desc
          %label 有効期限
          %span 必須
        .credit_cards-new__wrapper__form__expiration-date
          %select#exp_month{name: "exp_month", type: "text"}
            %option{value: ""} --
            %option{value: "1"}01
            %option{value: "2"}02
            %option{value: "3"}03
            %option{value: "4"}04
            %option{value: "5"}05
            %option{value: "6"}06
            %option{value: "7"}07
            %option{value: "8"}08
            %option{value: "9"}09
            %option{value: "10"}10
            %option{value: "11"}11
            %option{value: "12"}12
          %p 月
          %select#exp_year{name: "exp_year", type: "text"}
            %option{value: ""} --
            %option{value: "2020"}20
            %option{value: "2021"}21
            %option{value: "2022"}22
            %option{value: "2023"}23
            %option{value: "2024"}24
            %option{value: "2025"}25
            %option{value: "2026"}26
            %option{value: "2027"}27
            %option{value: "2028"}28
            %option{value: "2029"}29
          %p 年
          %br
        .credit_cards-new__wrapper__form__cvc
          %label セキュリティコード
          %span 必須
          = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3桁または4桁の番号", maxlength: "4", id: "cvc"
          #card_token
        .credit_cards-new__wrapper__form__submit
          = submit_tag "登録する", id: "token_submit"

= render 'shared/footer'

app/views/credit_cards/show.html.haml
.container
  = render "/shared/header"

%nav.nav-crumbs
  %ul
    %li 
      = link_to "#" do
        FURIMA
    %li
      = icon('fas', 'angle-right')
    %li 
      = link_to mypage_index_path do
        マイページ
    %li
      = icon('fas', 'angle-right')
    %li 
      支払い方法

.mypage-content
  .credit_cards-show
    .credit_cards-show__wrapper
      .credit_cards-show__wrapper__content-title
        支払い方法
      .credit_cards-show__wrapper__cards-index

        .credit_cards-show__wrapper__cards-index__title
          登録クレジットカード情報

        .credit_cards-show__wrapper__cards-index__detail

          .credit_cards-show__wrapper__cards-index__detail__left
            - if @card_brand == "American Express"
              = image_tag "#{@card_src}", height: '46', width: '46', alt: @card_brand, id: "card_image"
            - else
              = image_tag "#{@card_src}", height: '33', width: '46', alt: @card_brand, id: "card_image"

            .credit_cards-show__wrapper__cards-index__detail__left__card-number
              = "**** **** **** " + @default_card_information.last4
            .credit_cards-show__wrapper__cards-index__detail__left__expiration-date
              - exp_month = @default_card_information.exp_month.to_s
              - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
              = exp_month + " / " + exp_year
          .credit_cards-show__wrapper__cards-index__detail__right
            .credit_cards-show__wrapper__cards-index__detail__right__delete-button
              = form_tag(delete_credit_cards_path, method: :post, data: { confirm: "【確認】クレジットカード情報を削除してよろしいですか？\n（削除後も再登録可能です）" }, id: 'charge-form',  name: "inputForm") do
                %input{ type: "hidden", name: "card_id", value: "" }
                %button 削除する

= render "/shared/footer"