config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords     => "users/passwords"
  }
  # resources :users, only: [:index]
  devise_scope :user do
    get 'users/signuplist' => 'users/registrations#signuplist'
    post 'users/signuplist' => 'users/registrations#signuplist'
    post 'users/create' => 'users/registrations#create'
    get 'users/complete' => 'users/registrations#complete'
    # post 'users/complete_submit' => 'users/registrations#complete_submit'
    get 'users/index' => 'users/registrations#index'
    get 'users/:id' => 'users/registrations#show'
    # ↓な気もしますのでrails routesコマンドなどで確認してください
    # get 'signuplist' => 'users/registrations#signuplist'
  end

  resources :credit_cards, only: [:new, :show] do
    collection do
      post 'show',   to: 'credit_cards#show'
      post 'pay',    to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end

  resources :products, only: [:new,:create,:show,:edit,:update,:destroy] do
    collection do
      get 'category/get_category_children', to: 'products#get_category_children', defaults: { format: 'json' }
      get 'category/get_category_grandchildren', to: 'products#get_category_grandchildren', defaults: { format: 'json' }
      get 'update_done'
    end
    member do
      post 'purchase'
      get  'buy'
    end
  end
  
  resources :mypage, only: [:index] do
    collection do
      get :logout
      get :credit
    end
  end
  
  resources :users, only: [:new] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry
  validates :name, presence: true
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
end

app/models/postage_payer.rb
class Postage_payer < ActiveHash::Base
  self.data = [
  {id: 0, name: '選択してください'},
  {id: 1, name: '送料込み（出品者負担）'}, {id: 2, name: '着払い（購入者負担）'}
  ]
end

app/models/postagepayer.rb
class Postagepayer < ActiveHash::Base
  self.data = [
  {id: 0, name: '送料込み（出品者負担）'}, {id: 1, name: '着払い（購入者負担）'}
  ]
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
    {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
    {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
    {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
    {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
    {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
    {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
    {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
    {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
    {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
    {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
    {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
    {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
    {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
    {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
    {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}, {id: 48, name: '未定'}
  ]
end

app/models/product.rb
class Product < ApplicationRecord
  validates :productphotos, :name,:description,:price,:category_id,:productcondition_id,:prefecture_id,:postagepayer_id,:shippingdate_id, presence: true
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :productcondition
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :postagepayer
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :shippingdate
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :size
  belongs_to :category
  has_one :brand, dependent: :destroy
  has_many :productphotos, dependent: :destroy
  accepts_nested_attributes_for :productphotos,:brand,allow_destroy: true
  belongs_to :buyer, class_name: "User", optional: true, foreign_key: "buyer_id"

end

app/models/productcondition.rb
class Productcondition < ActiveHash::Base
  self.data = [
  {id: 0, name: '新品、未使用'}, {id: 1, name: '未使用に近い'}, {id: 2, name: '目立った傷や汚れなし'},
  {id: 3, name: 'やや傷やよごれあり'}, {id: 4, name: '傷やよごれあり'},{id: 5, name: '全体的に状態が悪い'}
  ]
end

app/models/productphoto.rb
class Productphoto < ApplicationRecord
  validates :src, presence: true
  mount_uploader :src, ImageUploader
  belongs_to :product
end

app/models/shipping_date.rb
class Shippoing_date < ActiveHash::Base
  self.data = [
  {id: 0, name: '選択してください'},
  {id: 1, name: '１〜２日で発送'}, {id: 2, name: '２〜３日で発送'},{id: ３, name: '４〜７日で発送'}
  ]
end

app/models/shippingdate.rb
class Shippingdate < ActiveHash::Base
  self.data = [
  {id: 0, name: '１〜２日で発送'}, {id: 1, name: '２〜３日で発送'},{id:2, name: '４〜７日で発送'}
  ]
end

app/models/size.rb
class Size < ActiveHash::Base
    self.data = [
        {id: 1, size: 'XXS以下'}, {id: 2, size: 'XS'}, {id: 3, size:'S'},
        {id: 4, size: 'M'}, {id: 5, size: 'L'}, {id: 6, size: 'XL'},{id: 7, size: '２XL'}, {id: 8, size: '３XL'}, 
        {id: 9, size: '４XL以上'},
        {id:10, size: 'FREE SIZE'}, {id: 11, size: '20cm以下'}, {id: 12, size: '20.5cm'}, 
        {id: 13, size: '21cm'},{id: 14, size: '21.5cm'}, {id: 15, size: '22cm'}, {id: 16, size: '22.5cm'},
        {id: 17, size: '23cm'}, {id: 18, size: '23.5cm'}, {id: 19, size: '24cm'},
        {id: 20, size: '24.5cm'}, {id: 21, size: '25cm'}, {id: 22, size: '25.5cm'},
        {id: 23, size: '26cm'}, {id: 24, size: '26.5cm'}, {id: 25, size: '27cm'},
        {id: 26, size: '27.5cm以上'}
    ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_save { self.email = email.downcase }
         
  extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to_active_hash :prefecture 

    validates :nickname,         presence: true
    validates :email,            presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    validates :password,         presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{7,30}+\z/i }
                                                                
    validates :first_name,       presence: true, format: { with: /\A[一-龥ぁ-ん]/}
    validates :family_name,      presence: true, format: { with: /\A[一-龥ぁ-ん]/}
    validates :first_name_rubi,  presence: true, format: { with: /\A[ァ-ヶー－]+\z/}
    validates :family_name_rubi, presence: true, format: { with: /\A[ァ-ヶー－]+\z/}
    validates :birthday,         presence: true 
   
    validates :zipcode,          presence: true,  format: { with: /\A\d{7}\z/ } #/^\d{7}$/
    validates :prefecture_code,  presence: true
    validates :city,             presence: true
    validates :house_number,     presence: true
    # validates :building_name    
    validates :phone_number,     allow_nil: true  , format: { with: /\A\d{10,11}\z/ } #/^\d{10,11}$/ 

  has_many :products
  has_one :credit_card, dependent: :destroy
  has_many :buyer_product, foreign_key: "buyer_id", class_name: "product", dependent: :destroy

end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def index
  end

  def logout
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def convert_to_jpy(price)
    "¥#{price.to_s(:delimited,delimiter: ',')}"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/create.html.haml
.wrapper
  .header02
    = image_tag asset_path('logo.png'), type: '', alt: '', size: "140x41"
  .items
    .body
      .photos
        .upload-box
          .style_formLabel
            %label
              出品画像
            %label.sign
              必須
            %p
            最大１０枚までアップロードできます
          .image-box
            = icon('fas', 'camera')
            %p
              ドラックアンドドロップ
            %p
              またはクリックしてファイルをダウンロード       
      .commodity
        .commodity__name
          .style_formLabel
            %p
              商品名
              %label.sign
                必須
            %input.style__formLabel
        .commodity__detail
          .style_formLabel
            %p
              商品の説明
              %label.sign
                必須
            %textarea(rows="8" cols="67")
      .details
        .style_formLabel
          %p
            カテゴリー
            %label.sign
              必須
          %select{name: "category"}
            %option{value:  "0"} 選択してください
            %option{value: "1"} レディース
            %option{value: "2"} メンズ
            %option{value: "3"} ベビー・キッズ
            %option{value: "4"} インテリア・住まい・小物
            %option{value: "5"} 本・音楽・ゲーム
            %option{value: "6"} おもちゃ・ホビー・グッズ
            %option{value: "7"} コスメ・香水・美容
            %option{value: "8"} 家電・スマホ・カメラ
            %option{value: "9"} スポーツ・レジャー
            %option{value: "10"} ハンドメイド
            %option{value: "11"} チケット
            %option{value: "12"} 自動車・オートバイ
            %option{value: "13"} その他
        .style_formLabel
          %p
            ブランド
          %input
        .style_formLabel
          %p
            商品の状態
            %label.sign
              必須
          %select{name: "category"}
            %option{value: "0"} 選択してください
            %option{value: "1"} 新品、未使用に近い
            %option{value: "2"} 目立った傷や汚れなし
            %option{value: "3"} やや汚れあり
            %option{value: "4"} 傷や汚れあり
            %option{value: "5"} 全体的に状態が悪い
      .delivery
        .style_formLabel
          %p
            配送料金の負担
            %label.sign
              必須
          %select{name: "status"}
            %option{value: "0"} 選択してください
            %option{value: "1"} 送料込み(出品者負担)
            %option{value: "2"} 着払い(購入者負担)
        .style_formLabel
          %p
            発送元の地域
            %label.sign
              必須
          %select{name: "region"}
            %option{ value: "0"} 選択してください
            %option{ value: "1"} 北海道
            %option{ value: "2"} 青森県
            %option{ value: "3"} 岩手県
            %option{ value: "4"} 宮城県
            %option{ value: "5"} 秋田県
            %option{ value: "6"} 山形県
            %option{ value: "7"} 福島県
            %option{ value: "8"} 茨城県
            %option{ value: "9"} 栃木県
            %option{ value: "10"} 群馬県
            %option{ value: "11"} 埼玉県
            %option{ value: "12"} 千葉県
            %option{ value: "13"} 東京都
            %option{ value: "14"} 神奈川県
            %option{ value: "15"} 新潟県
            %option{ value: "16"} 富山県
            %option{ value: "17"} 石川県
            %option{ value: "18"} 福井県
            %option{ value: "19"} 山梨県
            %option{ value: "20"} 長野県
            %option{ value: "21"} 岐阜県
            %option{ value: "22"} 静岡県
            %option{ value: "23"} 愛知県
            %option{ value: "24"} 三重県
            %option{ value: "25"} 滋賀県
            %option{ value: "26"} 京都府
            %option{ value: "27"} 大阪府
            %option{ value: "28"} 兵庫県
            %option{ value: "29"} 奈良県
            %option{ value: "30"} 和歌山県
            %option{ value: "31"} 鳥取県
            %option{ value: "32"} 島根県
            %option{ value: "33"} 岡山県
            %option{ value: "34"} 広島県
            %option{ value: "35"} 山口県
            %option{ value: "36"} 徳島県
            %option{ value:"37"} 香川県
            %option{ value: "38"} 愛媛県
            %option{ value: "39"} 高知県
            %option{ value: "40"} 福岡県
            %option{ value: "41"} 佐賀県
            %option{ value: "42"} 長崎県
            %option{ value: "43"} 熊本県
            %option{ value: "44"} 大分県
            %option{ value: "45"} 宮崎県
            %option{ value: "46"} 鹿児島県
            %option{ value: "47"} 沖縄県
            %option{ value: "48"} その他 
        .style_formLabel
          %p
            発送までの日数
            %label.sign
              必須
          %select{:name => "shippingDuration"}
            %option{value:"0"} 選択してください
            %option{value:"1"} 1~2日
            %option{value:"2"} 2~3日
            %option{value:"3"} 4~7日
      .price
        .price__celect
          %label
            販売価格
          %label.sign
            必須
          .price__celect__plate
            ￥
          %input{type: "number", value: "0",class: "profit"}
        .price__fee
          %p
            販売手数料
          %p
            ー
      .bottom
        .profit
          %p
            販売利益
          %p
            ー  
        .buttons    
          .buttons__sell
            出品する
          .buttons__save
            下書きに保存
          =link_to "#"do
            .buttons__back もどる
      .warning
        禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
  = render "/shared/footer02" 

app/views/items/index.html.haml
%h1 Items#index
%p Find me in app/views/items/index.html.erb

app/views/items/show.html.haml
.wrapper
  .header02
    = image_tag asset_path('logo.png'), type: '', alt: '', size: "140x41"
  .items
    .body
      .photos
        .upload-box
          .style_formLabel
            %label
              出品画像
            %label.sign
              必須
            %p
            最大１０枚までアップロードできます
          .image-box
            = icon('fas', 'camera')
            %p
              ドラックアンドドロップ
            %p
              またはクリックしてファイルをダウンロード       
      .commodity
        .commodity__name
          .style_formLabel
            %p
              商品名
              %label.sign
                必須
            %input.style__formLabel
        .commodity__detail
          .style_formLabel
            %p
              商品の説明
              %label.sign
                必須
            %textarea(rows="8" cols="67")
      .details
        .style_formLabel
          %p
            カテゴリー
            %label.sign
              必須
          %select{name: "category"}
            %option{value:  "0"} 選択してください
            %option{value: "1"} レディース
            %option{value: "2"} メンズ
            %option{value: "3"} ベビー・キッズ
            %option{value: "4"} インテリア・住まい・小物
            %option{value: "5"} 本・音楽・ゲーム
            %option{value: "6"} おもちゃ・ホビー・グッズ
            %option{value: "7"} コスメ・香水・美容
            %option{value: "8"} 家電・スマホ・カメラ
            %option{value: "9"} スポーツ・レジャー
            %option{value: "10"} ハンドメイド
            %option{value: "11"} チケット
            %option{value: "12"} 自動車・オートバイ
            %option{value: "13"} その他
        .style_formLabel
          %p
            ブランド
          %input
        .style_formLabel
          %p
            商品の状態
            %label.sign
              必須
          %select{name: "category"}
            %option{value: "0"} 選択してください
            %option{value: "1"} 新品、未使用に近い
            %option{value: "2"} 目立った傷や汚れなし
            %option{value: "3"} やや汚れあり
            %option{value: "4"} 傷や汚れあり
            %option{value: "5"} 全体的に状態が悪い
      .delivery
        .style_formLabel
          %p
            配送料金の負担
            %label.sign
              必須
          %select{name: "status"}
            %option{value: "0"} 選択してください
            %option{value: "1"} 送料込み(出品者負担)
            %option{value: "2"} 着払い(購入者負担)
        .style_formLabel
          %p
            発送元の地域
            %label.sign
              必須
          %select{name: "region"}
            %option{ value: "0"} 選択してください
            %option{ value: "1"} 北海道
            %option{ value: "2"} 青森県
            %option{ value: "3"} 岩手県
            %option{ value: "4"} 宮城県
            %option{ value: "5"} 秋田県
            %option{ value: "6"} 山形県
            %option{ value: "7"} 福島県
            %option{ value: "8"} 茨城県
            %option{ value: "9"} 栃木県
            %option{ value: "10"} 群馬県
            %option{ value: "11"} 埼玉県
            %option{ value: "12"} 千葉県
            %option{ value: "13"} 東京都
            %option{ value: "14"} 神奈川県
            %option{ value: "15"} 新潟県
            %option{ value: "16"} 富山県
            %option{ value: "17"} 石川県
            %option{ value: "18"} 福井県
            %option{ value: "19"} 山梨県
            %option{ value: "20"} 長野県
            %option{ value: "21"} 岐阜県
            %option{ value: "22"} 静岡県
            %option{ value: "23"} 愛知県
            %option{ value: "24"} 三重県
            %option{ value: "25"} 滋賀県
            %option{ value: "26"} 京都府
            %option{ value: "27"} 大阪府
            %option{ value: "28"} 兵庫県
            %option{ value: "29"} 奈良県
            %option{ value: "30"} 和歌山県
            %option{ value: "31"} 鳥取県
            %option{ value: "32"} 島根県
            %option{ value: "33"} 岡山県
            %option{ value: "34"} 広島県
            %option{ value: "35"} 山口県
            %option{ value: "36"} 徳島県
            %option{ value:"37"} 香川県
            %option{ value: "38"} 愛媛県
            %option{ value: "39"} 高知県
            %option{ value: "40"} 福岡県
            %option{ value: "41"} 佐賀県
            %option{ value: "42"} 長崎県
            %option{ value: "43"} 熊本県
            %option{ value: "44"} 大分県
            %option{ value: "45"} 宮崎県
            %option{ value: "46"} 鹿児島県
            %option{ value: "47"} 沖縄県
            %option{ value: "48"} その他 
        .style_formLabel
          %p
            発送までの日数
            %label.sign
              必須
          %select{:name => "shippingDuration"}
            %option{value:"0"} 選択してください
            %option{value:"1"} 1~2日
            %option{value:"2"} 2~3日
            %option{value:"3"} 4~7日
      .price
        .price__celect
          %label
            販売価格
          %label.sign
            必須
          .price__celect__plate
            ￥
          %input{type: "number", value: "0",class: "profit"}
        .price__fee
          %p
            販売手数料
          %p
            ー
      .bottom
        .profit
          %p
            販売利益
          %p
            ー  
        .buttons    
          .buttons__sell
            出品する
          .buttons__save
            下書きに保存
          =link_to "#"do
            .buttons__back もどる
      .warning
        禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
  = render "/shared/footer02" 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title FURIMA72a
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true
    = javascript_include_tag 'application', 'data-turbolinks-track': true
  %body
    = yield

app/views/shared/_footer.html.haml
.banner
  .banner-inner
    %h2.banner-inner__title だれでもかんたん、人生を変えるフリマアプリ
    %p.banner-inner__text 今すぐ無料ダウンロード！
    .banner-inner__icon
      = link_to "#" do
        = image_tag asset_path('Download_on_the_App_Store_Badge_JP_RGB_blk_100317.svg'), type: '', alt: '', class: 'abtn'
      = link_to "#" do
        = image_tag asset_path('google-play-badge.png'), type: '', alt: '', class: 'gbtn'
    
.footer
  %ul.footer-contents
    %li.footer-content
      %h2.footer-content__title FURIMAについて
      %ul
        %li
          = link_to "#" do
            会社概要（運営会社）
        %li
          = link_to "#" do
            プライバシーポリシー
        %li
          = link_to "#" do
            FURIMA利用規約
        %li
          = link_to "#" do
            ポイントに関する特約
    %li.footer-content
      %h2.footer-content__title FURIMAを見る
      %ul
        %li
          = link_to "#" do
            カテゴリー一覧
        %li
          = link_to "#" do
            ブランド一覧
    %li.footer-content
      %h2.footer-content__title ヘルプ＆ガイド
      %ul
        %li
          = link_to "#" do
            FURIMAガイド
        %li
          = link_to "#" do
            FURIMAロゴ利用ガイドライン
        %li
          = link_to "#" do
            お知らせ
  .footer-logo
    = link_to "#" do
      = image_tag asset_path('logo-white.png'), type: '', alt: ''
  %p.footer-mark © FURIMA
= link_to new_product_path do
  .footer-button
    .footer-button__text 出品する
    = image_tag asset_path('icon_camera.png'), type: '', alt: '', class: 'footer-button__icon'

app/views/shared/_footer01.html.haml
.footer01
  .nav 
    %ul.cleafix
      %li
        %a{href: '#'}プライバシーポリシー
      %li
        %a{href: '#'}FURIMA利用規約
      %li
        %a{href: '#'}特定商取引に関する表記
  %a{href: root_path, class: "footer01__logo"}
    = image_tag asset_path('logo.png'), type: '', alt: ''
  %p.footer-mark © FURIMA,Inc

app/views/shared/_footer02.html.haml
.footer
  %ul.footer-contents
    %li.footer-content
      %h2.footer-content__title FURIMAについて
      %ul
        %li
          = link_to "#" do
            会社概要（運営会社）
        %li
          = link_to "#" do
            プライバシーポリシー
        %li
          = link_to "#" do
            FURIMA利用規約
        %li
          = link_to "#" do
            ポイントに関する特約
    %li.footer-content
      %h2.footer-content__title FURIMAを見る
      %ul
        %li
          = link_to "#" do
            カテゴリー一覧
        %li
          = link_to "#" do
            ブランド一覧
    %li.footer-content
      %h2.footer-content__title ヘルプ＆ガイド
      %ul
        %li
          = link_to "#" do
            FURIMAガイド
        %li
          = link_to "#" do
            FURIMAロゴ利用ガイドライン
        %li
          = link_to "#" do
            お知らせ
  .footer-logo
    %p.footer-mark © FURIMA
    = link_to "#" do
      = image_tag asset_path('logo-white.png'), type: '', alt: ''
  %p.footer-mark © FURIMA

app/views/shared/_header.html.haml
.body
  .header
    .header-inner
      .innner-top
        %h1.innner-icon
          = link_to root_path, class: "innner-icon__a" do
            %span.innner-icon__image
              = image_tag asset_path('logo.png'), type: '', alt: '', size: "140x41"
        .innner-top__box
          %form{"accept-charset": "UTF-8", action: "#", method: "get"}
            %input{name: "utf8", type: "hidden", value: "✓"}/
            %input{class:'innner-top__box-input', name: "key", placeholder: "キーワードから探す" }/
            %button{type: "submit"}
              %span.innner-top__box__icon
                = image_tag asset_path('icon-search 1.png'), type: '', alt: ''
      .innner-lists
        %ul.lists-left
          %li.lists-left__item
            = link_to "#", class: "lists-left__item-category" do
              カテゴリー
          %li.lists-left__item
            = link_to "#", class:"lists-left__item-brand" do
              ブランド
        %ul.lists-right
          %li.lists-right__item
            -if user_signed_in?
              = link_to mypage_index_path, class:"lists-right__item-mypage" do
                マイページ
              = link_to destroy_user_session_path, class:"lists-right__item-destroy", method: :delete do
                ログアウト
            -else   
              = link_to new_user_session_path, class:"lists-right__item-login" do
                ログイン
              = link_to new_user_registration_path, class:"lists-right__item-register" do
                新規会員登録
            

app/views/shared/_header01.html.haml
.header01
  .header01__logo
    = link_to root_path, class: "header01__icon" do
      = image_tag asset_path('logo.png'), type: '', alt: '', size: "140x41" 