config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords     => "users/passwords"
  }
  # resources :users, only: [:index]
  devise_scope :user do
    get 'users/signuplist' => 'users/registrations#signuplist'
    post 'users/signuplist' => 'users/registrations#signuplist'
    post 'users/create' => 'users/registrations#create'
    get 'users/complete' => 'users/registrations#complete'
    # post 'users/complete_submit' => 'users/registrations#complete_submit'
    get 'users/index' => 'users/registrations#index'
    get 'users/:id' => 'users/registrations#show'
    # ↓な気もしますのでrails routesコマンドなどで確認してください
    # get 'signuplist' => 'users/registrations#signuplist'
  end

  resources :credit_cards, only: [:new, :show] do
    collection do
      post 'show',   to: 'credit_cards#show'
      post 'pay',    to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end

  resources :products, only: [:new,:create,:show,:edit,:update,:destroy] do
    collection do
      get 'category/get_category_children', to: 'products#get_category_children', defaults: { format: 'json' }
      get 'category/get_category_grandchildren', to: 'products#get_category_grandchildren', defaults: { format: 'json' }
      get 'update_done'
    end
    member do
      post 'purchase'
      get  'buy'
    end
  end
  
  resources :mypage, only: [:index] do
    collection do
      get :logout
      get :credit
    end
  end
  
  resources :users, only: [:new] 
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def index
  end

  def logout
  end
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/views/mypage/credit.html.haml
.container
  = render "/shared/header"

%nav.nav-crumbs
  %ul
    %li 
      = link_to "#" do
        FURIMA
    %li
      = icon('fas', 'angle-right')
    %li 
      = link_to mypage_index_path do
        マイページ
    %li
      = icon('fas', 'angle-right')
    %li 
      支払い方法
%main.mypage-main
  .mypage-top
    .mypage-side-bar
      .mypage-nav
        %ul.mypage-nav__list
          %li
            = link_to mypage_index_path do
              マイページ
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              お知らせ
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              やることリスト
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              いいね！一覧
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              出品する
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              下書き一覧
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              出品した商品ー出品中
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              出品した商品ー取引中
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              出品した商品ー売却済み
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              購入した商品ー取引中
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              購入した商品ー過去の取引
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              ニュース一覧
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              評価一覧
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              ガイド
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              お問い合わせ
              = icon('fas', 'chevron-right')
        %h2.mypage-nav__head-title
          メルペイ
        %ul.mypage-nav__list
          %li
            = link_to "#" do
              残高・振込申請
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              ポイント
              = icon('fas', 'chevron-right')
          %h2.mypage-nav__head-title
            設定
          %li
            = link_to "#" do
              プロフィール
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              発送元・お届け先住所変更
              = icon('fas', 'chevron-right')
          %li
            = link_to credit_mypage_index_path, class: "active" do
              支払い方法
              = icon('fas', 'chevron-right', class: "active")
          %li
            = link_to "#" do
              メール/パスワード
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              本人情報
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              電話番号の確認
              = icon('fas', 'chevron-right')
          %li
            = link_to logout_mypage_index_path do
              ログアウト
              = icon('fas', 'chevron-right')
    .mypage-content
      .mypage-content__credit
        %h2 支払い方法
        .mypage-content__credit-inner
          %section
            .credit-inner__content
              %h3 クレジットカード一覧
          %section.credit-inner__add-card
            .credit-inner__card-btn
              = link_to new_credit_card_path do
                = icon('fas', 'credit-card')
                クレジットカードを追加する
          .credit-inner__setting-regist
            = link_to "#" do
              %span 支払い方法について
              = icon('fas', 'chevron-right')

= render "/shared/footer"

app/views/mypage/index.html.haml
.container
  = render "/shared/header"

%nav.nav-crumbs
  %ul
    %li 
      = link_to "#" do
        FURIMA
    %li
      = icon('fas', 'angle-right')
    %li 
      = link_to mypage_index_path do
        マイページ

%main.mypage-main
  .mypage-top
    .mypage-side-bar
      .mypage-nav
        %ul.mypage-nav__list
          %li
            = link_to mypage_index_path, class: "active" do
              マイページ
              = icon('fas', 'chevron-right', class: "active")
          %li
            = link_to "#" do
              お知らせ
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              やることリスト
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              いいね！一覧
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              出品する
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              下書き一覧
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              出品した商品ー出品中
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              出品した商品ー取引中
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              出品した商品ー売却済み
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              購入した商品ー取引中
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              購入した商品ー過去の取引
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              ニュース一覧
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              評価一覧
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              ガイド
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              お問い合わせ
              = icon('fas', 'chevron-right')
        %h2.mypage-nav__head-title
          メルペイ
        %ul.mypage-nav__list
          %li
            = link_to "#" do
              残高・振込申請
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              ポイント
              = icon('fas', 'chevron-right')
          %h2.mypage-nav__head-title
            設定
          %li
            = link_to "#" do
              プロフィール
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              発送元・お届け先住所変更
              = icon('fas', 'chevron-right')
          %li
            = link_to credit_mypage_index_path do
              支払い方法
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              メール/パスワード
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              本人情報
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              電話番号の確認
              = icon('fas', 'chevron-right')
          %li
            = link_to logout_mypage_index_path do
              ログアウト
              = icon('fas', 'chevron-right')

    .mypage-content
      .mypage-content__user-icon
        = link_to "#" do
          = image_tag asset_path('member_photo_noimage_thumb.png'), type: '', alt: '', height: '60', width: '60'
          %h2 UserName
          .mypage-count
            %div
              評価
              %span 
                0
            %div
              出品数
              %span 
                0
      %section.mypage-content__notification-todo
        %ul.mypage-tabs
          %li
            %h2
              = link_to "#" do
                お知らせ
          %li.active
            %h2
              = link_to "#" do
                やることリスト
        .tab-content
          %ul.mypage-item-list
            %li 現在、やることリストはありません
      %section.mypage-content__tab-container
        %h2 購入した商品
        %ul.mypage-tabs
          %li.active
            %h2
              = link_to "#" do
                取引中
          %li
            %h2
              = link_to "#" do
                過去の取引
        .tab-content
          %ul.mypage-item-list
            %li 取引中の商品がありません
          
= render "/shared/footer"

app/views/mypage/logout.html.haml
.container
  = render "/shared/header"

%nav.nav-crumbs
  %ul
    %li 
      = link_to "#" do
        FURIMA
    %li
      = icon('fas', 'angle-right')
    %li 
      = link_to mypage_index_path do
        マイページ
    %li
      = icon('fas', 'angle-right')
    %li 
      ログアウト

%main.mypage-main
  .mypage-top
    .mypage-side-bar
      .mypage-nav
        %ul.mypage-nav__list
          %li
            = link_to mypage_index_path do
              マイページ
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              お知らせ
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              やることリスト
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              いいね！一覧
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              出品する
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              下書き一覧
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              出品した商品ー出品中
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              出品した商品ー取引中
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              出品した商品ー売却済み
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              購入した商品ー取引中
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              購入した商品ー過去の取引
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              ニュース一覧
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              評価一覧
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              ガイド
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              お問い合わせ
              = icon('fas', 'chevron-right')
        %h2.mypage-nav__head-title
          メルペイ
        %ul.mypage-nav__list
          %li
            = link_to "#" do
              残高・振込申請
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              ポイント
              = icon('fas', 'chevron-right')
          %h2.mypage-nav__head-title
            設定
          %li
            = link_to "#" do
              プロフィール
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              発送元・お届け先住所変更
              = icon('fas', 'chevron-right')
          %li
            = link_to credit_mypage_index_path do
              支払い方法
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              メール/パスワード
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              本人情報
              = icon('fas', 'chevron-right')
          %li
            = link_to "#" do
              電話番号の確認
              = icon('fas', 'chevron-right')
          %li
            = link_to logout_mypage_index_path, class: "active" do
              ログアウト
              = icon('fas', 'chevron-right', class: "active")
    .mypage-content
      .mypage-content__logout
        %form(action="#")
          .mypage-content__logout-btn
            %button{type: "submit", class:'logout-btn'} ログアウト

= render "/shared/footer"