config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords     => "users/passwords"
  }
  # resources :users, only: [:index]
  devise_scope :user do
    get 'users/signuplist' => 'users/registrations#signuplist'
    post 'users/signuplist' => 'users/registrations#signuplist'
    post 'users/create' => 'users/registrations#create'
    get 'users/complete' => 'users/registrations#complete'
    # post 'users/complete_submit' => 'users/registrations#complete_submit'
    get 'users/index' => 'users/registrations#index'
    get 'users/:id' => 'users/registrations#show'
    # ↓な気もしますのでrails routesコマンドなどで確認してください
    # get 'signuplist' => 'users/registrations#signuplist'
  end

  resources :credit_cards, only: [:new, :show] do
    collection do
      post 'show',   to: 'credit_cards#show'
      post 'pay',    to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end

  resources :products, only: [:new,:create,:show,:edit,:update,:destroy] do
    collection do
      get 'category/get_category_children', to: 'products#get_category_children', defaults: { format: 'json' }
      get 'category/get_category_grandchildren', to: 'products#get_category_grandchildren', defaults: { format: 'json' }
      get 'update_done'
    end
    member do
      post 'purchase'
      get  'buy'
    end
  end
  
  resources :mypage, only: [:index] do
    collection do
      get :logout
      get :credit
    end
  end
  
  resources :users, only: [:new] 
end

app/models/product.rb
class Product < ApplicationRecord
  validates :productphotos, :name,:description,:price,:category_id,:productcondition_id,:prefecture_id,:postagepayer_id,:shippingdate_id, presence: true
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :productcondition
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :postagepayer
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :shippingdate
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :size
  belongs_to :category
  has_one :brand, dependent: :destroy
  has_many :productphotos, dependent: :destroy
  accepts_nested_attributes_for :productphotos,:brand,allow_destroy: true
  belongs_to :buyer, class_name: "User", optional: true, foreign_key: "buyer_id"

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, except: [:index, :new, :create,:get_category_children,:get_category_grandchildren]
  before_action :set_card, only: [:buy, :purchase]
  before_action :move_to_index_buy, only: [:buy, :purchase]
  before_action :move_to_index_purchased, only: [:buy, :purchase]

  def index
    @products = Product.all.order('id DESC').limit(4)
  end

  def show
  @user = User.find(@product.seller_id)
  @sell_price = @product.price * 1.1 
  end
  
  def new
    if user_signed_in?
      @product = Product.new
      @product.productphotos.new
      @product.build_brand
      @category_parent_array = ["---"]
      @category_parent_array = Category.where(ancestry: nil)
    else
      redirect_to new_user_session_path
    end
  end

  def get_category_children
    @category_children = Category.find(params[:parent_id]).children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find(params[:child_id]).children
  end
  
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to root_path
    else
      redirect_to new_product_path
    end
  end

  def buy
    Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_SECRET_KEY]

    customer = Payjp::Customer.retrieve(@card.customer_id)
    @creditcard_information = customer.cards.retrieve(@card.card_id)
    @card_brand = @creditcard_information.brand 
    case @card_brand
    when "Visa"
      @card_src = "visa.png"
    when "JCB"
      @card_src = "jcb.png"
    when "MasterCard"
      @card_src = "master.png"
    when "American Express"
      @card_src = "americanexpress.png"
    when "Diners Club"
      @card_src = "dinersclub.png"
    when "Discover"
      @card_src = "discover.gif"
    end

    @user = User.find_by(id: current_user.id)
  end
    
  def purchase
    Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_SECRET_KEY]

    charge = Payjp::Charge.create(
      amount: @product.price,
      customer: Payjp::Customer.retrieve(@card.customer_id),
      currency: 'jpy'
    )

    @product_buyer= Product.find(params[:id])
    if @product_buyer.update(buyer_id: current_user.id)
      redirect_to root_path, notice: '購入しました'
    else
      render :show, notice: '購入できませんでした'
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to product_path
    else
      render :edit
    end
  end

  def destroy
    if @product.destroy
    redirect_to root_path
    else
      render :show
    end
  end

  def update_done
    @product_update = Product.order("updated_at DESC").first
  end


  private

  def product_params
   params.require(:product).permit(:name,:description,:price,:category_id,:productcondition_id,:prefecture_id,:postagepayer_id,:shippingdate_id,productphotos_attributes: [:src, :_destroy,:id,:product_id],brand_attributes: [:name,:id,:_destroy]).merge(seller_id: current_user.id)
  end
  
  def set_product
    @product = Product.find(params[:id])
    @product_photos = @product.productphotos
  end

  def set_card
    @card = CreditCard.find_by(user_id: current_user.id) if CreditCard.find_by(user_id: current_user.id).present?
  end

  def move_to_index_buy
    @product = Product.find(params[:id])
    redirect_to root_path if current_user.id == @product.buyer_id
  end

  def move_to_index_purchased
    @product = Product.find(params[:id])
    redirect_to root_path if @product.buyer_id.present? 
  end

end

app/helpers/products_helper.rb
module ProductsHelper
  def convert_to_jpy(price)
    "¥#{price.to_s(:delimited,delimiter: ',')}"
  end
end

app/views/products/_form.html.haml
.wrapper
  .header02
    = image_tag asset_path('logo.png'), type: '', alt: '', size: "140x41"
  .items
    .body
      = form_with model: @product ,local: true do |f|
        .photos
          .upload-box
            .style_formLabel
              %label
                出品画像
              %label.sign
                必須
              %p
              最大１０枚までアップロードできます
            .image-box
              #image-box
                %label    
                  %i.fas.fa-camera
                  #previews
                    - if @product.persisted? 
                      - @product.productphotos.each_with_index do |image, i|
                        = image_tag image.src.url, data: { index: i }, width: "100", height: '100'
                  = f.fields_for :productphotos do |i|
                    .js-file_group{"data-index" => "#{i.index}"}
                      = i.file_field :src, class: 'js-file'
                      %span.js-remove
                        削除
                    
                      -if @product.persisted?
                        = i.check_box :_destroy, data:{ index: i.index }, class: 'hidden-destroy'
                    -if @product.persisted?
                      .js-file_group{"data-index" => "#{@product.productphotos.count}"}
                        = file_field_tag :src, name: "product[productphotos_attributes][#{@product.productphotos.count}][src]", class: 'js-file'
                        %span.js-remove
                          削除
                  %p
                    ドラックアンドドロップ
                  %p
                    またはクリックしてファイルをダウンロード 
        .commodity
          .commodity__name
            .style_formLabel
              %p
                商品名
                %label.sign
                  必須
                = f.text_field :name 
          .commodity__detail
            .style_formLabel
              %p
                商品の説明
                %label.sign
                  必須
                = f.text_area :description, class: "commodity__detail__description"
        .details
          .exhibitionPage
            .exhibitionPage__main
              .exhibitionPage__main__contents
                
                .exhibitionPage__main__contents__detail
                  .exhibitionPage__main__contents__detail__title
                    %p 商品の詳細
                  .exhibitionPage__main__contents__detail__category
                    .exhibitionPage__main__contents__detail__category__title
                      %label.sab-title カテゴリー
                      %span.required 必須
                  
                    .exhibitionPage__main__contents__detail__category__choose
                      = f.collection_select :category_id, Category.where(ancestry: nil), :id, :name, {prompt: "選択してください"}, {id: 'parent_category'}

                    //.size-sellect_form
                    //  = f.collection_select :size_id, Size.find([1,2]),:id, :size,class:"input"
                    
          .details__brand
            = f.fields_for :brand do |b|
              %span ブランド
              %span.form-require-gray 任意
              = b.text_field :name, placeholder: "例）シャネル", value: "", class: "input-default"
                    
          .style_formLabel
            %span.identification__form__field__label 商品の状態
            %span.identification__form__field__arbitrary 必須
            .identification__form__field--input.icon-relative
              = f.collection_select :productcondition_id, Productcondition.all, :id, :name, {prompt:"選択してください"},class: 'input' 
        .delivery
          .style_formLabel
            %span.identification__form__field__lavel 発送料金の負担 
            %span.identification__form__field__arbitrary 必須
            = f.collection_select :postagepayer_id, Postagepayer.all, :id, :name, {prompt:"選択してください"},class: 'input'
          .style_formLabel
            %span.identification__form__field__lavel 発送元の地域
            %span.identification__form__field__arbitrary 必須
            = f.collection_select :prefecture_id, Prefecture.all, :id, :name,{prompt:"選択してください"}, class: 'input'
          .style_formLabel
            %span.identification__form__field__lavel 発送までの日数
            %span.identification__form__field__arbitrary 必須
            = f.collection_select :shippingdate_id, Shippingdate.all, :id, :name, {prompt:"選択してください"},class: 'input'
          .price
            .price__celect
              .labels
                %p.identification__form__field__lavel 
                  販売価格
                %p.identification__form__field__arbitrary 
                  必須
              .price__celect__plate
                ￥
              = f.number_field :price
            .price__fee
              %p
                販売手数料 (10%)
              %p#handlefee
                
              %p
                円
          .bottom
            .profit
              %p
                販売利益
              %p#profit

              %p
                円
                
            .buttons    
              = f.submit "出品する", class: "buttons__sell"
              .buttons__save 下書きに保存
              =link_to root_path do
                .buttons__back もどる
              .warning
                禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
= render "/shared/footer02" 

app/views/products/_new.html.haml
.wrapper
  .header02
    = image_tag asset_path('logo.png'), type: '', alt: '', size: "140x41"
  .items
    .body
      = form_with model: @product ,local: true do |f|
        .photos
          .upload-box
            .style_formLabel
              %label
                出品画像
              %label.sign
                必須
              %p
              最大１０枚までアップロードできます
            .image-box
              #image-box_id
                %label    
                  %i.fas.fa-camera
                  = f.fields_for :productphotos do |i|
                    .js-file_group{"data-index" => "#{i.index}"}
                      = i.file_field :src, class: 'js-file'
                    -if @product.persisted?
                      = i.check_box :_destroy, data:{ index: i.index }, class: 'hidden-destroy'
                  -if @product.persisted?
                    .js-file_group{"data-index" => "#{@product.productphotos.count}"}
                      = file_field_tag :src, name: "product[productphotos_attributes][#{@product.productphotos.count}][src]", class: 'js-file'

                  %p
                    ドラックアンドドロップ
                  %p
                    またはクリックしてファイルをダウンロード 
        .commodity
          .commodity__name
            .style_formLabel
              %p
                商品名
                %label.sign
                  必須
                = f.text_field :name 
          .commodity__detail
            .style_formLabel
              %p
                商品の説明
                %label.sign
                  必須
                = f.text_area :description, class: "commodity__detail__description"
        .details
          .exhibitionPage
            .exhibitionPage__main
              .exhibitionPage__main__contents
                
                .exhibitionPage__main__contents__detail
                  .exhibitionPage__main__contents__detail__title
                    %p 商品の詳細
                  .exhibitionPage__main__contents__detail__category
                    .exhibitionPage__main__contents__detail__category__title
                      %label.sab-title カテゴリー
                      %span.required 必須
                    .exhibitionPage__main__contents__detail__category__choose
                      = f.collection_select :category_id, Category.where(ancestry: nil), :id, :name, {prompt: '---'}, {id: 'parent_category'}
                    .size-sellect_form
                      = f.collection_select :size_id, Size.find([1,2]),:id, :size,class:"input"
                    
          .details__brand
            = f.fields_for :brand do |b|
              %span ブランド
              %span.form-require-gray 任意
              = b.text_field :name, placeholder: "例）シャネル", value: "", class: "input-default"
                    
          .style_formLabel
            %span.identification__form__field__label 商品の状態
            %span.identification__form__field__arbitrary 必須
            .identification__form__field--input.icon-relative
              = f.collection_select :productcondition_id, Productcondition.all, :id, :name, class: 'input' 
        .delivery
          .style_formLabel
            %span.identification__form__field__lavel 発送料金の負担 
            %span.identification__form__field__arbitrary 必須
            = f.collection_select :postagepayer_id, Postagepayer.all, :id, :name, class: 'input'
          .style_formLabel
            %span.identification__form__field__lavel 発送元の地域
            %span.identification__form__field__arbitrary 必須
            = f.collection_select :prefecture_id, Prefecture.all, :id, :name, class: 'input'
          .style_formLabel
            %span.identification__form__field__lavel 発送までの日数
            %span.identification__form__field__arbitrary 必須
            = f.collection_select :shippingdate_id, Shippingdate.all, :id, :name, class: 'input'
          .price
            .price__celect
              .labels
                %p.identification__form__field__lavel 
                  販売価格
                %p.identification__form__field__arbitrary 
                  必須
              .price__celect__plate
                ￥
              = f.number_field :price
            .price__fee
              %p
                販売手数料 (10%)
              %p#handlefee
                
              %p
                円
          .bottom
            .profit
              %p
                販売利益
              %p#profit

              %p
                円
                
            .buttons    
              = f.submit "出品する", class: "buttons__sell"
              .buttons__save 下書きに保存
              =link_to "product_path" do
                .buttons__back もどる
              .warning
                禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
= render "/shared/footer02" 

app/views/products/buy.html.haml
= render 'shared/header01'

%main.products-purchase-wrapper
  %section.products-purchase-wrapper__buy-item-container
    %h2.products-purchase-wrapper__buy-item-container__buy-head 購入内容の確認

    .products-purchase-buy-content
      .products-purchase-buy-content__inner
        .products-purchase-buy-content__inner__item-box
          %h3.products-purchase-buy-content__inner__item-box__image
            %img.products-purchase-buy-content__inner__item-box__image--img-loaded{src: @product.productphotos.first.src.url}/
          .products-purchase-buy-content__inner__item-box__detail
            %p.products-purchase-buy-content__inner__item-box__detail__name
              = @product.name
            %p.products-purchase-buy-content__inner__item-box__detail__price-ja
              %span
                = @product.price.to_s(:delimited)
                円
              %span.products-purchase-buy-content__inner__item-box__detail__price-ja__shipping-fee （税込）送料込み

    %section.products-purchase-buy-content
      .products-purchase-buy-content__inner
        = form_with(url: purchase_product_path, local: true, method: :post) do |form|
          %ul.products-purchase-buy-price-table
            %li.products-purchase-buy-price-row
              .products-purchase-buy-price-cell.buy-price-cell-label 支払い金額
              .products-purchase-buy-price-cell
                %span
                  = @product.price.to_s(:delimited)
                  円

          %section.buy-user-info
            .products-purchase-buy-content__inner
              .clearfix
                %h3.products-purchase-l-left 支払い方法
              %p.products-purchase-buy-user-info-text
                %br/
                クレジットカード
                %br/
                = "**** **** **** " + @creditcard_information.last4
                %br/
                - mm = @creditcard_information.exp_month.to_s
                - yy = @creditcard_information.exp_year.to_s.slice(2,3)
                = mm + " / " + yy
              %figure.products-purchase-buy-card-logo
                = image_tag "#{@card_src}", height: '33', width: '46', alt: @card_brand, id: "card_image"

          %section.buy-user-info
            .products-purchase-buy-content__inner
              .clearfix
                %h3.products-purchase-l-left 配送先
              %address.products-purchase-buy-user-info-text
                %p
                  %br
                  = "〒" + "#{@user.zipcode}"
                  %br
                  = Prefecture.find_by_id(@user.prefecture_code).name
                  %br
                  = @user.city
                  = @user.house_number
                  = @user.building_name
                  %br
                  =@user.family_name
                  =@user.first_name
          %section.buy-user-info
            %p.products-purchase-has-info-text
              郵便局/コンビニ受取をご希望の方は、購入後に
              %span.products-purchase-bold> 取引画面
              から受取場所を変更をすることが可能です。出品者が発送作業を開始した後は受取場所の変更ができませんので、早めに変更を行ってください。
          %label.products-purchase-btn-default.btn-red.bold
            = form.submit '購入する'

= render 'shared/footer01'

app/views/products/create.html.haml
.wrapper
  .header
    %img(src="assets/logo.png" alt="ロゴ" width="140" height="41")
  .items
    .body
      .photos
        .upload-box
          .style_formLabel
            %label
              出品画像
            %label.sign
              必須
            %p
            最大１０枚までアップロードできます
          .image-box
            = icon('fas', 'camera')
            %p
              ドラックアンドドロップ
            %p
              またはクリックしてファイルをダウンロード       
      .commodity
        .commodity__name
          .style_formLabel
            %p
              商品名
              %label.sign
                必須
            %input{:size => "67px"}
        .commodity__detail
          .style_formLabel
            %p
              商品の説明
              %label.sign
                必須
            %textarea(rows="8" cols="67")
      .details
        .style_formLabel
          %p
            カテゴリー
            %label.sign
              必須
          %select{:name => "category"}
            %option{:value => "0"} 選択してください
            %option{:value => "1"} レディース
            %option{:value => "2"} メンズ
            %option{:value => "3"} ベビー・キッズ
            %option{:value => "4"} インテリア・住まい・小物
            %option{:value => "5"} 本・音楽・ゲーム
            %option{:value => "6"} おもちゃ・ホビー・グッズ
            %option{:value => "7"} コスメ・香水・美容
            %option{:value => "8"} 家電・スマホ・カメラ
            %option{:value => "9"} スポーツ・レジャー
            %option{:value => "10"} ハンドメイド
            %option{:value => "11"} チケット
            %option{:value => "12"} 自動車・オートバイ
            %option{:value => "13"} その他
        .style_formLabel
          %p
            ブランド
          %input
        .style_formLabel
          %p
            商品の状態
            %label.sign
              必須
          %select{:name => "category"}
            %option{:value => "0"} 選択してください
            %option{:value => "1"} 新品、未使用に近い
            %option{:value => "2"} 目立った傷や汚れなし
            %option{:value => "3"} やや汚れあり
            %option{:value => "4"} 傷や汚れあり
            %option{:value => "5"} 全体的に状態が悪い
      .delivery
        .style_formLabel
          %p
            配送料金の負担
            %label.sign
              必須
          %select{:name => "status"}
            %option{:value => "0"} 選択してください
            %option{:value => "1"} 送料込み(出品者負担)
            %option{:value => "2"} 着払い(購入者負担)
        .style_formLabel
          %p
            発送元の地域
            %label.sign
              必須
          %select{:name => "region"}
            %option{:value => "0"} 選択してください
            %option{ value: "1"} 北海道
            %option{ value: "2"} 青森県
            %option{ value: "3"} 岩手県
            %option{ value: "4"} 宮城県
            %option{ value: "5"} 秋田県
            %option{ value: "6"} 山形県
            %option{ value: "7"} 福島県
            %option{ value: "8"} 茨城県
            %option{ value: "9"} 栃木県
            %option{ value: "10"} 群馬県
            %option{ value: "11"} 埼玉県
            %option{ value: "12"} 千葉県
            %option{ value: "13"} 東京都
            %option{ value: "14"} 神奈川県
            %option{ value: "15"} 新潟県
            %option{ value: "16"} 富山県
            %option{ value: "17"} 石川県
            %option{ value: "18"} 福井県
            %option{ value: "19"} 山梨県
            %option{ value: "20"} 長野県
            %option{ value: "21"} 岐阜県
            %option{ value: "22"} 静岡県
            %option{ value: "23"} 愛知県
            %option{ value: "24"} 三重県
            %option{ value: "25"} 滋賀県
            %option{ value: "26"} 京都府
            %option{ value: "27"} 大阪府
            %option{ value: "28"} 兵庫県
            %option{ value: "29"} 奈良県
            %option{ value: "30"} 和歌山県
            %option{ value: "31"} 鳥取県
            %option{ value: "32"} 島根県
            %option{ value: "33"} 岡山県
            %option{ value: "34"} 広島県
            %option{ value: "35"} 山口県
            %option{ value: "36"} 徳島県
            %option{ value:"37"} 香川県
            %option{ value: "38"} 愛媛県
            %option{ value: "39"} 高知県
            %option{ value: "40"} 福岡県
            %option{ value: "41"} 佐賀県
            %option{ value: "42"} 長崎県
            %option{ value: "43"} 熊本県
            %option{ value: "44"} 大分県
            %option{ value: "45"} 宮崎県
            %option{ value: "46"} 鹿児島県
            %option{ value: "47"} 沖縄県
            %option{:value => "48"} その他 
        .style_formLabel
          %p
            発送までの日数
            %label.sign
              必須
          %select{:name => "shippingDuration"}
            %option{:value => "0"} 選択してください
            %option{:value => "1"} 1~2日
            %option{:value => "2"} 2~3日
            %option{:value => "3"} 4~7日
      .price
        .price__celect
          %label
            販売価格
          %label.sign
            必須
          .price__celect__plate
            ￥
          %input{:type => "number", :value => "0",:class => "profit"}
        .price__fee
          %p
            販売手数料
          %p
            ー
      .bottom
        .profit
          %p
            販売利益
          %p
            ー  
        .button    
          .button__sell
            出品する
          .button__save
            下書きに保存
          .button__back
            もどる
      .warning
        禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
  = render "/shared/footer" 

app/views/products/new.html.haml
= render partial: 'form'

app/views/products/show.html.haml
.container
  = render "/shared/header"

%nav.nav-crumbs
  %ul
    %li 
      = link_to "#"do
        FURIMA
    %li
      = icon('fas', 'angle-right')
    %li 
      = link_to @product.category.name
    %li
      = icon('fas', 'angle-right')
    %li 
      = @product.name
.main
  .main-show
    .inner
      .inner-content
        .item-box
          %h2.item-box__name
            = @product.name
          .item-box__img
            %ul
              %li
                = image_tag @product_photos[0].src.to_s
                %ul
                  %li
                    - if @product_photos[1].blank?
                      = image_tag asset_path('logo.png'), type: '', alt: ''
                    - else
                      = image_tag @product_photos[1].src.to_s
                  %li
                    - if @product_photos[2].blank?
                      = image_tag asset_path('logo.png'), type: '', alt: ''
                    - else
                      = image_tag @product_photos[2].src.to_s
                  %li
                    - if @product_photos[3].blank?
                      = image_tag asset_path('logo.png'), type: '', alt: ''
                    - else
                      = image_tag @product_photos[3].src.to_s
          .item-box__price
            %span 
              ¥
              = @sell_price.to_i
            .item-box__price-detail
              %span (税込)
              %span
                - if @product.postagepayer_id == 0
                  送料込み
                - else 
                  着払い
              - if user_signed_in? && @product.seller_id == current_user.id
                = link_to edit_product_path(@product), class: "edit-btn" do
                  商品の編集
                %p
                  or
                = link_to product_path(@product), class: "delete-btn", method: :delete do
                  この商品を削除する
            
              - elsif @product.buyer_id.present? 
                = link_to "#", class: "purchase-btn-gray" do
                  売り切れました

              - elsif current_user.blank?
                = link_to new_user_session_path, data: {confirm: '【確認】購入はログインが必要です。移動しますか？' }, class: "purchase-btn" do
                  購入画面に進む

              - elsif current_user.credit_card.present?
                = link_to buy_product_path, class: "purchase-btn" do
                  購入画面に進む

              - elsif current_user.credit_card.blank?
                = link_to new_credit_card_path, data: { confirm: '【確認】クレジットカード登録が必要です。登録画面に移動しますか？' }, class: "purchase-btn" do
                  購入画面に進む

          .item-box__text
            = @product.description
          .item-box__table
            %table
              %tbody
                %tr
                  %th 出品者
                  %td 
                    = @user.nickname
                %tr
                  %th カテゴリー
                  %td
                    = link_to @product.category.name
                %tr
                  %th ブランド
                  %td
                    = @product.brand_id
                %tr
                  %th 商品の状態
                  %td 
                    = @product.productcondition.name
                %tr
                  %th 配送料の負担
                  %td 
                    = @product.postagepayer.name
                %tr
                  %th 発送元の地域
                  %td 
                    = @product.prefecture.name
                %tr
                  %th 発送日の目安
                  %td 
                    = @product.shippingdate.name
          .optional-area
            %ul
              %li.like-btn
                = icon('fas', 'star')
                お気に入り 15
            %ul
              %li.optional-btn
                = link_to "#" do
                  = icon('fas', 'flag')
                  不適切な商品の通報
        .comment-box
          = form_for "#" do |f|
            %textarea(name="comment-body" required="required")
            %p
              相手のことを考え丁寧なコメントを心がけましょう。
              %br
              不快な言葉遣いなどは利用制限や退会処分となることがあります。
            %button(name="button" type="submit")
              = icon('fas', 'comment')
              コメントする
        %ul.links
          %li
            = link_to "#" do
              = icon('fas', 'angle-left')
              %span 前の商品
          %li
            = link_to "#" do
              %span 後ろの商品
              = icon('fas', 'angle-right')
        .related-items
          = link_to "#{@product.category.name}をもっと見る"

  = render "/shared/footer"